all:
	(cd hdrs    && make && make install)
	(cd scripts && make && make install)
	(cd util    && make && make install)

clean:
	(cd hdrs    && make clean)
	(cd scripts && make clean)
	(cd util    && make clean)
