all:
	(cd hdrs    && make && make install)
	(cd scripts && make && make install)
	(cd util    && make && make install)
	(cd pngs    && make && make install)
	(cd tiles   && make && make install)
	(cd HPXGap  && make && make install)

clean:
	(cd hdrs    && make clean)
	(cd scripts && make clean)
	(cd util    && make clean)
	(cd pngs    && make clean)
	(cd tiles   && make clean)
	(cd HPXGap  && make clean)
